module.exports = {
  content: ["./**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#83d6c4",
        "secondary-container": "#d4dffe",
        "inverse-surface": "#2d3135",
        "on-primary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#3c475f",
        "primary": "#00478d",
        "surface-container-high": "#e6e8ee",
        "on-error": "#ffffff",
        "background": "#f7f9ff",
        "on-primary-container": "#c8daff",
        "primary-container": "#005eb8",
        "secondary-fixed-dim": "#bbc6e4",
        "tertiary": "#005247",
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed": "#9ff2e0",
        "on-surface": "#191c20",
        "on-tertiary-fixed": "#00201b",
        "on-error-container": "#93000a",
        "primary-fixed": "#d6e3ff",
        "surface-bright": "#f7f9ff",
        "error": "#ba1a1a",
        "surface": "#f7f9ff",
        "on-secondary-container": "#57627d",
        "on-tertiary-fixed-variant": "#005046",
        "secondary": "#535e78",
        "surface-container-low": "#f2f3f9",
        "outline-variant": "#c2c6d4",
        "outline": "#727783",
        "on-primary": "#ffffff",
        "tertiary-container": "#036c5e",
        "inverse-primary": "#a9c7ff",
        "primary-fixed-dim": "#a9c7ff",
        "on-surface-variant": "#424752",
        "on-primary-fixed-variant": "#00468c",
        "surface-container": "#eceef4",
        "surface-dim": "#d8dae0",
        "on-background": "#191c20",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#97ead8",
        "inverse-on-surface": "#eff1f6",
        "on-tertiary": "#ffffff",
        "surface-tint": "#005db6",
        "on-secondary-fixed": "#101b32",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e2e8",
        "surface-container-highest": "#e0e2e8"
      },
      fontFamily: {
        "headline": ["Public Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
